linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 25
  goconst:
    min-len: 2
    min-occurrences: 2
  errcheck:
    check-type-assertions: true
  gocritic:
    disabled-checks:
      - ifElseChain
  nakedret:
    max-func-lines: 15

run:
  skip-dirs:
    - mock

linters:
  enable:
    - gocritic
    - stylecheck
    - goimports
    - gosec
    - unconvert
    - unparam
    - gochecknoinits
    - gosec
    - nakedret
    - whitespace
    - gosimple
    - bodyclose
    - dogsled
    - rowserrcheck
  disable:
    - maligned
    - lll
    - dupl
    - gochecknoglobals
